Book navigation
sillsdev/appbuilder-pwa pull request #100
Opened 2022-12-11 20:51 UTC by Jason-Lopez8

Created a "SelectList" similar to SelectGrid.

Got relatively far, hit a roadblock with the "Book, Chapter, and Verse" tabs at the top. They're in the same list format as the book collections.

2023-01-23 21:34 UTC, chrisvire commented
@Jason-Lopez8 I like the list display.  However, you code is how of date with main and doesn't have the changes for switching themes and the SelectList isn't themed correctly.

You will need to rebase your code (get with me or @jakedcolbert on how to do this). Then look at @jakedcolbert PR on dropdown styles (and/or ask him for help) on theming the select list.

Also, the dropdown arrow next to the book name is not colored correctly.

2023-01-27 06:45 UTC, jakedcolbert requested changes

2023-01-27 06:45 UTC, jakedcolbert commented on src/lib/components/SelectList.svelte
> +    let tableColor = colors('main', 'BackgroundColor');
Use the $s store to retrieve colors. I believe everything you need is in under the ui.select-list-button key.

2023-01-27 14:12 UTC, chrisvire commented
@Jason-Lopez8 I have merged @jakedcolbert's PR on Dropdown Style.  You should rebase this PR on main and use what he suggests.  If you need help with the rebase, let me know.

2023-01-31 16:03 UTC, chrisvire commented
@Jason-Lopez8 For the List, you need to use book names instead of the book abbreviations.

Anything else you are waiting on doing?

2023-02-02 18:00 UTC, chrisvire approved these changes

2023-02-02 18:00 UTC, merged