Use CSS Vars for Colors
sillsdev/appbuilder-pwa pull request #194
Opened 2023-04-20 19:15 UTC by chrisvire

Scripture App Builder has been changed to generate sab-app.css with CSS vars for colors. Also, clean up where items are added to the `<head>`

The example_data folder needed to be updated for new CSS and I am not sure what the previous project was used. So I updated the project and included a README with the Google Drive location.

2023-04-20 19:18 UTC, chrisvire commented on static/override-sab.css
> +body {
SAB stopped excluding margin-top, margin-bottom which was a bit of a hack.  We should exclude it from inside the PWA.

2023-04-20 23:51 UTC, chrisvire commented
@FyreByrd Could you look at the main README.md?

2023-04-21 00:00 UTC, FyreByrd requested changes
There is one line in `README.md` that needs to be updated to reflect the changes in `package.json`, other than that, this looks fine.

2023-04-21 00:10 UTC, FyreByrd approved these changes
Looks good to me

2023-04-21 13:28 UTC, davidmoore1 approved these changes

2023-04-21 13:28 UTC, merged