#249 Reimplement Audio
sillsdev/appbuilder-pwa pull request #294
Opened 2023-06-26 16:59 UTC by ChristopherRankin

This changes how audio highlighting is implemented. This does not currently work.

2023-07-13 17:57 UTC, chrisvire commented
@ChristopherRankin The merge conflicts are probably due to me fixing the prettier config.  I can help you with fixing this.

2023-07-13 20:28 UTC, ChristopherRankin commented
Noticed that the progress bar when no timing is not synchronizing correctly.

2023-07-14 12:45 UTC, chrisvire approved these changes

2023-07-14 12:46 UTC, chrisvire requested changes
Waiting on progress bar

2023-07-17 19:26 UTC, closed without merging