#286 Implement layout menu toggler in sidebar
sillsdev/appbuilder-pwa pull request #318
Opened 2023-07-05 16:21 UTC by jakedcolbert

Add a drawer menu option to display the layout option menu. Using the collectionSelector id, call the showModal() function to show the menu.

This is achieved by: 
- Adding a button and divider to the drawer with a translated label
- Adding visibility functionality by including the option if the `config.mainFeatures['layout-config-change-nav-drawer-menu']` configuration is true.
- Adding an `onclick` handler to the button to execute "collectionSelector.showModal()"

2023-07-05 16:27 UTC, jakedcolbert commented
Ready for review @chrisvire

2023-07-06 15:12 UTC, chrisvire commented
![image](https://github.com/sillsdev/appbuilder-pwa/assets/517814/5a9c1cd3-f235-4993-a102-6c7a7e9ac7d7)

2023-07-06 15:13 UTC, chrisvire requested changes
Fix the `&amp;` displaying

2023-07-06 17:43 UTC, jakedcolbert commented on src/lib/components/Sidebar.svelte
> +                        onclick="collectionSelector.showModal()"
@chrisvire

2023-07-06 18:32 UTC, chrisvire commented on src/lib/components/Sidebar.svelte
> +                        onclick="collectionSelector.showModal()"
Yeah, that is not good.  We need to figure something else out.

2023-07-06 20:46 UTC, closed without merging

2023-07-06 21:01 UTC, jakedcolbert commented
All I did was rebase. Help!

2023-07-06 21:01 UTC, jakedcolbert commented
All I did was rebase. Help!!