Feature/convert reversal index/685
sillsdev/appbuilder-pwa pull request #747
Opened 2024-12-04 00:34 UTC by aidanpscott

2024-12-04 15:52 UTC, chrisvire commented on convert/convertReverseIndex.ts
> +        return;
This show throw an exception and stop the convert process, not just return.

2024-12-04 22:29 UTC, chrisvire requested changes
This approach doesn't work for words that start with accented characters.  Here is a project:

https://drive.google.com/file/d/1fFksgphKDmZ1BsaepeGBrTqyCABoyJlf/view?usp=drive_link

There words were not included in your statc/reversal/language/fr/*.json files:

à côté  1296
à l'intérieur   81
à l’aise        1149
à la maison     477
à la place de (emp. à l’arabe)  901

œil     1178
œuf     727

In the native app, they were under a and o.

2024-12-09 00:21 UTC, aidanpscott reviewed
Changes have been made

2024-12-09 21:18 UTC, chrisvire approved these changes
👍

2024-12-09 21:18 UTC, merged